# Generated by Django 3.1.1 on 2020-10-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20201003_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Likes',
            new_name='likes',
        ),
    ]
